name: WDIO Android Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-tests:
    runs-on: macos-latest   # Required for Android emulator

    env:
      DEVICE_NAME: ${{ secrets.DEVICE_NAME }}
      PLATFORM_NAME: ${{ secrets.PLATFORM_NAME }}
      PLATFORM_VERSION: ${{ secrets.PLATFORM_VERSION }}
      APPIUM_HOSTL: ${{ secrets.APPIUM_HOST }}
      APPIUM_PORT: ${{ secrets.APPIUM_PORT }}
      APP_PATH: ${{ secrets.APP_PATH }}

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install Appium
      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      # 5. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 6. Start Android Emulator
      - name: Start Emulator
        run: |
          sdkmanager "system-images;android-33;google_apis;x86_64"
          avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --device "pixel"
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      # 7. Start Appium
      - name: Start Appium Server
        run: appium --base-path /wd/hub &
      
      # 8. Run WDIO Tests
      - name: Run WDIO Tests
        run: npx wdio run wdio.conf.js

      # 9. Upload Allure Results
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
